config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :videos
  resources :weathers
  resources :songs
  resources :playlists
  resources :moods






  post '/user_playlist', to: 'playlists#user_playlist'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mood.rb
class Mood < ApplicationRecord
  has_many :playlists
  has_many :songs, through: :playlists
end

app/models/playlist.rb
class Playlist < ApplicationRecord

  belongs_to :weather
  belongs_to :mood
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :playlist
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :videos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user, :optional => true


  has_many :playlists
  has_many :songs, through: :playlists
end

app/models/weather.rb
class Weather < ApplicationRecord
    has_many :playlists
    has_many :songs, through: :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
  playlists_path
end
def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
def iframe_action
      response.headers.delete "X-Frame-Options"
      render_something
    end


end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  def index
    @moods = Mood.all
  end

  def show
    @mood = Mood.find(params[:id])
  end
  def new

    @mood = Mood.new
  end

  def create

    @mood = Mood.create(mood_params)
    redirect_to moods_path(@moood)

  end
  def update
    @mood = mood.update(mood_params)
    redirect_to mood_path(@mood)

  end
    def destroy
    @mood= Mood.destroy(params[:id])
    redirect_to moods_path

  end

  def mood_params
    params.require(:mood).permit(:emoji)
  end


end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController


  def index
    @song = Song.all
    @playlist = Playlist.new
    @mood = Mood.all
    @weather = Weather.all
    @playlists = Playlist.all
  end

  def show
    @mood = Mood.all

    @song = Song.all
    @playlist = Playlist.find(params[:id])
  end
  def new
    @song = Song.all
    @mood = Mood.all
    @weather = Weather.all
    @playlist = Playlist.new
  end

  def user_playlist

    @playlist = Playlist.all.find_by(mood_id:params["playlist"]["mood_id"],weather_id:params["playlist"]["weather_id"])

    redirect_to playlist_path(@playlist)
    # look at form inputs (mood_id and weather_id)
    # find playlist associated with those
    # redirect_to that playlist_path(@playlist)
  end



end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])

  end

  def new
    @playlist = Playlist.all
    @weather = Weather.all
    @mood = Mood.all
    @song = Song.new
    #redirect_to songs_path(@song)
  end

  def create
    # @songs = Song.all
    # if @mood == "happy" && @weather == "sunny"
    # elsif @mood == "happy" && @weather == "cloudy"
    # elsif @mood == "happy" && @weather == "rainy"
    # elsif @mood == "happy" && @weather == "thunderstorms"
    # elsif @mood == "angry" && @weather == "sunny"
    # elsif @mood == "angry" && @weather == "cloudy"
    # elsif @mood == "angry" && @weather == "rainy"
    # elsif @mood == "angry" && @weather == "thunderstorms"
    # elsif @mood == "sad" && @weather == "sunny"
    # elsif @mood == "sad" && @weather == "cloudy"
    # elsif @mood == "sad" && @weather == "rainy"
    # elsif @mood == "sad" && @weather == "thunderstorms"

  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:youtube_embed)
    end
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  def index
    @weathers = Weather.all
  end

  def show
    @weather = Weather.find(params[:id])
  end

  def new

    @weather = Weather.new
  end

  def create
    @weather = Weather.create(weather_params)
    redirect_to weathers_path(@weather)


  end

  def weather_params
    params.require(:weather).permit(:weather_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head >
    <title>MoodSwing</title>




<%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



  </head>

  <body style="background-image: url(<%= asset_path 'bg-masthead.jpg' %>)" class="text-black text-center"  >
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
    <p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up for MoodSwing", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
  </body>
</html>

app/views/moods/index.html.erb
<h1>All Moods:</h1>
<h3><% @moods.each do |mood| %></h3>
<h3><%=link_to mood.emoji, mood_path(mood), class: "song-link" %></h3>



<%end%>

app/views/playlists/index.html.erb
<!-- <h1>All Playlists:</h1>
<h3><% @playlists.each do |playlist| %></h3>
<h3><%= link_to playlist.name, playlist_path(playlist), class: "song-link" %></h3>



<%end%> -->

<div class="header-container text-center">.
<h1>Welcome to Mood Swing</h1>
<h3>Choose your Mood and Weather</h3>
</div>


<div class="flex-container text-center" >
<%= form_for @playlist, url: user_playlist_path do |f| %>
<%= f.label :mood %>
<%= f.collection_select :mood_id, @mood, :id, :emoji%>
<%= f.label :weather %>
<%= f.collection_select :weather_id, @weather, :id, :weather_type %>

<%= f.submit "Mood Swing" %>
<% end %>

<div>
<%= link_to 'Add New Videos', new_video_path %>
</div>
<div>
<%= link_to 'View My Videos', videos_path %>
</div>
</div>

app/views/playlists/new.html.erb
<div class="header-container text-center">
<h1>Welcome to Mood Swing</h1>

</div>


<div>
<%= form_for @playlist do |f| %>
<%= f.label :mood %>
<%= f.collection_select :mood_id, @moods, :id, :emoji%>
<%= f.label :weather %>
<%= f.collection_select :weather_id, @weathers, :id, :weather_type %>
<%= f.submit "Mood Swing" %>
<% end %>
</div>
</div>

app/views/playlists/show.html.erb
<div class="playlist-container text-center text-black">
<h1>Your Mood & Weather Choices</h1>


<h3><% @playlist.songs.each do |song| %></h3>
<h3><%=link_to "#{song.song_name} - #{song.artist_name}", song_path(song), class: "song-link" %></h3>



<%end%>
</div>
<div>
<%=link_to "All Songs", songs_path, class: "song-link" %>
</div>
<div>
<%= link_to "Back to Playlists", playlists_path, class: "song-link" %>
</div>

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
<%= f.label :mood %>
<%= f.collection_select :mood_id, @mood, :id, :emoji%>
<%= f.label :weather %>
<%= f.collection_select :weather_id, @weather, :id, :weather_type %>
<%= f.submit "Play Song" %>
<% end %>

app/views/songs/index.html.erb
<div class="all-songs text-cente"style="background-image: url(<%= asset_path 'bg-masthead.jpg' %>) " >
<h1>All Songs:</h1>
<h3><%= link_to "Back", playlists_path, class: "song-link" %> </h3>
<h3><% @songs.each do |song| %></h3>
<h3 ><%=link_to "#{song.song_name} - #{song.artist_name}", song_path(song), class: "song-link"%></h3>



<%end%>
</div>

app/views/songs/show.html.erb
<div class="songs-container text-center text-black" >
<h1>Your Mood and Weather Choices Say You are Feeling like this Song</h1>

<iframe width="1000" height="500" src='https://www.youtube.com/embed/<%=@song.url%>' frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>


<h3><%= link_to "Back", playlist_path(@song.playlist), class: "song-link" %> </h3>
</div>

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :youtube_embed %>
    <%= form.text_field :youtube_embed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Videos</h1>
<div>

<table>
  <thead>
    <tr>
      <th>Youtube Embed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.youtube_embed %></td>
        
        <td><%= link_to 'Show', video %></td>

        <td><%= link_to 'Edit', edit_video_path(video) %></td>

        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Video', new_video_path %>
<%=link_to "All Songs", songs_path, class: "song-link" %>
<%= link_to "Back playlists", playlists_path, class: "song-link" %>

app/views/videos/new.html.erb
<h1> Add New Video</h1>

<%= render 'form', video: @video %>


<%= link_to 'Back', videos_path %>
<%=link_to "All Songs", songs_path, class: "song-link" %>
<%= link_to "Back playlists", playlists_path, class: "song-link" %>

app/views/videos/show.html.erb
<div class="video-container">
<p id="notice"><%= notice %></p>

<p>
  <strong> Add Youtube embed:</strong>
  <%= @video.youtube_embed %>

  <iframe width="1000" height="500" src='https://www.youtube.com/embed/<%= @video.youtube_embed %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen></iframe>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>
<%=link_to "All Songs", songs_path, class: "song-link" %>
<%= link_to "Back playlists", playlists_path, class: "song-link" %> 
</div>

app/views/weathers/index.html.erb
<h1>All Weather:</h1>
<h3><% @weathers.each do |weather| %></h3>
<h3><%=link_to weather.weather_type, weather_path(weather), class: "song-link" %></h3>



<%end%>